name: Build application

on:
  push:
    branches: [ main ]       # trigger when you push to main
  pull_request:
    branches: [ main ]       # trigger for PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest   # fresh Linux VM

    steps:
  
      - name: Checkout
        uses: actions/checkout@v4

      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm          

    
      - name: Install dependencies
        run: npm ci           

      
      - name: Build app
        run: npm run build    

     
      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 7
