name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out the repo
      - uses: actions/checkout@v4

      # 2️⃣  Install Node and cache npm packages
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # 3️⃣  Install project deps (reproducible)
      - name: Install dependencies
        run: npm ci

      # 4️⃣  Run Cypress headless
      #
      #    • cypress-io/github-action handles:
      #        – installing the Cypress binary (and caching it)
      #        – starting the dev server
      #        – waiting until it's responsive
      #        – running `cypress run`
      #
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start                 # launches dev server on port 9300
          wait-on: 'http://localhost:9300' # ping until server is ready
          wait-on-timeout: 120             # seconds to wait before failing
          command: npm run cy:run          # your headless script

      # 5️⃣  (Optional) upload videos & screenshots when tests fail
      - name: Upload Cypress artifacts
        if: failure()                      # only save if tests failed
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
          retention-days: 7
