name: Lint & Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Fetch your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣  Install Node and use npm-cache for speed
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # 3️⃣  Clean, reproducible install
      - name: Install dependencies
        run: npm ci

      # 4️⃣  Run Prettier in **check-only** mode
      #     • Fails if any file is not correctly formatted
      - name: Check formatting (Prettier)
        run: npx prettier --check .

      # 5️⃣  Run ESLint
      #     • Adjust script/paths if your project uses a custom lint command
      - name: Lint (ESLint)
        run: npm run lint
