name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      # 🔧 Auto-fix formatting issues
      - name: Run Prettier (auto-fix)
        run: npx prettier --write .

      # 💾 Commit formatting fixes back to repo
      - name: Commit formatting fixes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-format with Prettier" || echo "No changes to commit"
          git push || echo "No changes to push"

      # ✅ Final formatting check (optional safety net)
      - name: Check formatting (Prettier)
        run: npx prettier --check .

      - name: Lint (ESLint)
        run: npm run lint
