name: Unit Tests

# ➊ Run on every push or PR to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest # clean Linux VM

    steps:
      # ➋ Check out repository code
      - name: Checkout
        uses: actions/checkout@v4

      # ➌ Install Node 18 and set up npm cache
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm # caches ~/.npm automatically

      # ➍ Install dependencies from package-lock.json
      - name: Install dependencies
        run: npm ci # reproducible install

      # ➎ Run Jest test suite once (non-watch, CI mode)
      - name: Run unit tests
        run: npm run test:unit
        # if your script is simply "test", use: npm test
